# Generated by Django 4.0.1 on 2022-07-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=15, verbose_name='Nombre Equipo')),
                ('puntos_equipo', models.IntegerField(default=0, verbose_name='Puntos')),
                ('goles_favor', models.IntegerField(default=0, verbose_name='Goles a Favor')),
                ('goles_contra', models.IntegerField(default=0, verbose_name='Goles en Contra')),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('pais', models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brasil'), ('UR', 'Uruguay'), ('PE', 'Peru'), ('CO', 'Colombia'), ('PA', 'Paraguay'), ('CH', 'Chile'), ('EC', 'Ecuador'), ('BO', 'Bolivia'), ('VE', 'Venezuela')], max_length=15, verbose_name='Pais')),
                ('valoracion', models.IntegerField(blank=True, null=True, verbose_name='Valoracion')),
                ('posicion', models.CharField(blank=True, choices=[('Arquero', 'Arquero'), ('Defensor', 'Defensor'), ('Mediocampista', 'Mediocampista'), ('Delantero', 'Delantero')], max_length=15, null=True, verbose_name='Posicion')),
                ('velocidad', models.IntegerField(blank=True, null=True, verbose_name='Velocidad')),
                ('regate', models.IntegerField(blank=True, null=True, verbose_name='Regate')),
                ('pase', models.IntegerField(blank=True, null=True, verbose_name='Pase')),
                ('tiro', models.IntegerField(blank=True, null=True, verbose_name='Tiro')),
                ('defensa', models.IntegerField(blank=True, null=True, verbose_name='Defensa')),
                ('fisico', models.IntegerField(blank=True, null=True, verbose_name='Fisico')),
                ('goles', models.IntegerField(default=0, verbose_name='Goles')),
            ],
        ),
    ]
