# Generated by Django 4.0.1 on 2022-07-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='en_uso',
            field=models.BooleanField(blank=True, null=True, verbose_name='En Uso'),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='titular',
            field=models.BooleanField(blank=True, null=True, verbose_name='Titular'),
        ),
    ]
