# Generated by Django 4.0.1 on 2022-07-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_equipos_en_uso_jugadores_titular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Posicion Tabla')),
                ('fecha', models.IntegerField(blank=True, null=True, verbose_name='Fecha')),
                ('equipo_local', models.CharField(max_length=25, verbose_name='Equipo Local')),
                ('goles_local', models.IntegerField(blank=True, default=0, null=True, verbose_name='Goles Local')),
                ('goles_visitante', models.IntegerField(blank=True, default=0, null=True, verbose_name='Goles Visitante')),
                ('equipo_visitante', models.CharField(max_length=25, verbose_name='Equipo Visitante')),
            ],
        ),
    ]
