# Generated by Django 4.0.1 on 2023-04-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_calendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores_Rivales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('pais', models.CharField(max_length=15, verbose_name='Pais')),
                ('valoracion', models.IntegerField(verbose_name='Valoracion')),
                ('posicion', models.CharField(max_length=15, verbose_name='Posicion')),
            ],
        ),
    ]
