# Generated by Django 4.0.1 on 2023-05-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_jugadores_rivales_goles'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores_rivales',
            name='titular',
            field=models.BooleanField(blank=True, null=True, verbose_name='Titular'),
        ),
    ]
