# Generated by Django 4.0.1 on 2023-06-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_jugadores_rivales_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='forma',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Forma'),
        ),
        migrations.AddField(
            model_name='jugadores_rivales',
            name='forma',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Forma'),
        ),
    ]
